# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(27292B)
$foreground = rgb(CEDEE8)
$color0 = rgb(4C4E51)
$color1 = rgb(191F28)
$color2 = rgb(1E232D)
$color3 = rgb(4F495D)
$color4 = rgb(404F66)
$color5 = rgb(70627D)
$color6 = rgb(56788D)
$color7 = rgb(B1C7D5)
$color8 = rgb(7C8B95)
$color9 = rgb(212935)
$color10 = rgb(282F3C)
$color11 = rgb(6A617C)
$color12 = rgb(556988)
$color13 = rgb(9583A6)
$color14 = rgb(73A0BC)
$color15 = rgb(B1C7D5)
