# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010000)
$foreground = rgb(F1ECE9)
$color0 = rgb(010000)
$color1 = rgb(252422)
$color2 = rgb(2D2B29)
$color3 = rgb(5B5653)
$color4 = rgb(71635A)
$color5 = rgb(89817C)
$color6 = rgb(A09691)
$color7 = rgb(E2DBD8)
$color8 = rgb(9E9997)
$color9 = rgb(32302E)
$color10 = rgb(3C3A37)
$color11 = rgb(7A726E)
$color12 = rgb(978478)
$color13 = rgb(B7ACA5)
$color14 = rgb(D6C8C1)
$color15 = rgb(E2DBD8)
