# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000105)
$foreground = rgb(F8F8F7)
$color0 = rgb(000105)
$color1 = rgb(17262E)
$color2 = rgb(1A2830)
$color3 = rgb(403B47)
$color4 = rgb(824F5C)
$color5 = rgb(B28673)
$color6 = rgb(B0B0AE)
$color7 = rgb(ECEDEB)
$color8 = rgb(A5A6A4)
$color9 = rgb(1F333E)
$color10 = rgb(223540)
$color11 = rgb(564E5F)
$color12 = rgb(AD697B)
$color13 = rgb(EDB299)
$color14 = rgb(EAEBE8)
$color15 = rgb(ECEDEB)
